name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Build & Push
        run: |
          docker build -t devopsaiacr123.azurecr.io/aksapp:${{ github.sha }} ./aksapp
          docker push devopsaiacr123.azurecr.io/aksapp:${{ github.sha }}

      - name: Helm Deploy
        run: |
          helm upgrade aksapp ./aksapp/helm-chart --install --set image.tag=${{ github.sha }}
